"""Top-level package for ideagraph.

The public API is the generic knowledge-graph core (:mod:`ideagraph.kg`) — typed
:class:`Node` / :class:`Edge` in a :class:`KnowledgeGraph`, with a
:class:`Profile` supplying the vocabulary and rules for a domain — plus the
library index and semantic-search helpers built on top.
"""

from __future__ import annotations

from ideagraph.core import (
    SEP,
    compute_digest,
    global_id,
    hash_file,
    is_global_id,
    parse_global_id,
)
from ideagraph.kg import (
    Diagnostic,
    Edge,
    EdgeRule,
    KnowledgeGraph,
    Node,
    NodeRule,
    Profile,
    available_profiles,
    dumps_prov,
    extract_subgraph,
    from_prov,
    get_profile,
    loads_prov,
    register_profile,
    to_prov,
)
from ideagraph.kg.persistence import (
    SCHEMA_VERSION,
    dumps_graph,
    graph_from_document,
    graph_to_document,
    load_graph,
    loads_graph,
    save_graph,
)
from ideagraph.kg.profiles import (
    ARTICLE,
    ASSERTION_TYPES,
    CROSS_ARTICLE_TYPES,
    DISCOURSE_TYPES,
    PROJECT,
    RESEARCH,
    STATEMENT_TYPES,
    ActivityKind,
    ClaimStatus,
    Coverage,
    EvidenceKind,
    EvidenceRelation,
    NodeType,
    ProvenancePredicate,
    StatementStatus,
    StatementType,
    ValidationResult,
    apply_all,
    apply_validation,
    coverage,
    mark_stale,
    validate_all,
    validate_node,
)
from ideagraph.kg.reporting import render_node_report, render_report
from ideagraph.library import IndexResult, Library, SearchHit
from ideagraph.semantic import DEFAULT_MODEL, Embedder, SentenceTransformerEmbedder
from ideagraph.version import __version__

__all__ = [
    "ARTICLE",
    "ASSERTION_TYPES",
    "CROSS_ARTICLE_TYPES",
    "DEFAULT_MODEL",
    "DISCOURSE_TYPES",
    "PROJECT",
    "RESEARCH",
    "SCHEMA_VERSION",
    "SEP",
    "STATEMENT_TYPES",
    "ActivityKind",
    "ClaimStatus",
    "Coverage",
    "Diagnostic",
    "Edge",
    "EdgeRule",
    "Embedder",
    "EvidenceKind",
    "EvidenceRelation",
    "IndexResult",
    "KnowledgeGraph",
    "Library",
    "Node",
    "NodeRule",
    "NodeType",
    "Profile",
    "ProvenancePredicate",
    "SearchHit",
    "SentenceTransformerEmbedder",
    "StatementStatus",
    "StatementType",
    "ValidationResult",
    "__version__",
    "apply_all",
    "apply_validation",
    "available_profiles",
    "compute_digest",
    "coverage",
    "dumps_graph",
    "dumps_prov",
    "extract_subgraph",
    "from_prov",
    "get_profile",
    "global_id",
    "graph_from_document",
    "graph_to_document",
    "hash_file",
    "is_global_id",
    "load_graph",
    "loads_graph",
    "loads_prov",
    "mark_stale",
    "parse_global_id",
    "register_profile",
    "render_node_report",
    "render_report",
    "save_graph",
    "to_prov",
    "validate_all",
    "validate_node",
]
