"""Top-level package for ideagraph."""

from __future__ import annotations

from ideagraph.core import (
    ASSERTION_TYPES,
    Activity,
    ActivityKind,
    Claim,
    ClaimCoverage,
    ClaimStatus,
    CrossReference,
    Diagnostic,
    DigestResolver,
    Evidence,
    EvidenceKind,
    EvidenceRelation,
    NodeType,
    ProvenanceGraph,
    ProvenancePredicate,
    ProvenanceRelation,
    Statement,
    StatementStatus,
    StatementType,
    ValidationResult,
    apply_all,
    apply_validation,
    claim_coverage,
    compute_digest,
    coverage,
    diagnose,
    evidence_changed,
    find_stale_claims,
    find_stale_evidence,
    global_id,
    hash_file,
    is_global_id,
    mark_stale_claims,
    parse_global_id,
    validate_all,
    validate_claim,
)
from ideagraph.library import Edge, IndexResult, Library, SearchHit
from ideagraph.persistence import (
    SCHEMA_VERSION,
    dumps_graph,
    graph_from_document,
    graph_to_document,
    load_graph,
    loads_graph,
    save_graph,
)
from ideagraph.prov import dumps_prov, from_prov, loads_prov, to_prov
from ideagraph.reporting import render_claim_report, render_report
from ideagraph.semantic import DEFAULT_MODEL, Embedder, SentenceTransformerEmbedder
from ideagraph.version import __version__

__all__ = [
    "ASSERTION_TYPES",
    "DEFAULT_MODEL",
    "SCHEMA_VERSION",
    "Activity",
    "ActivityKind",
    "Claim",
    "ClaimCoverage",
    "ClaimStatus",
    "CrossReference",
    "Diagnostic",
    "DigestResolver",
    "Edge",
    "Embedder",
    "Evidence",
    "EvidenceKind",
    "EvidenceRelation",
    "IndexResult",
    "Library",
    "NodeType",
    "ProvenanceGraph",
    "ProvenancePredicate",
    "ProvenanceRelation",
    "SearchHit",
    "SentenceTransformerEmbedder",
    "Statement",
    "StatementStatus",
    "StatementType",
    "ValidationResult",
    "__version__",
    "apply_all",
    "apply_validation",
    "claim_coverage",
    "compute_digest",
    "coverage",
    "diagnose",
    "dumps_graph",
    "dumps_prov",
    "evidence_changed",
    "find_stale_claims",
    "find_stale_evidence",
    "from_prov",
    "global_id",
    "graph_from_document",
    "graph_to_document",
    "hash_file",
    "is_global_id",
    "load_graph",
    "loads_graph",
    "loads_prov",
    "mark_stale_claims",
    "parse_global_id",
    "render_claim_report",
    "render_report",
    "save_graph",
    "to_prov",
    "validate_all",
    "validate_claim",
]
