# Generated by Django 5.2.16 on 2026-07-22 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Graph",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("article_id", models.CharField(blank=True, default="", max_length=200)),
                ("title", models.CharField(blank=True, default="", max_length=500)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_graphs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["slug"],
            },
        ),
        migrations.CreateModel(
            name="Edge",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("edge_id", models.CharField(max_length=200)),
                ("type", models.CharField(max_length=64)),
                ("source", models.CharField(max_length=200)),
                ("target", models.CharField(max_length=400)),
                ("data", models.JSONField()),
                (
                    "graph",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="edges", to="graphs.graph"
                    ),
                ),
            ],
            options={
                "ordering": ["graph", "type", "edge_id"],
                "indexes": [
                    models.Index(fields=["graph", "source"], name="graphs_edge_graph_i_911c6b_idx"),
                    models.Index(fields=["graph", "target"], name="graphs_edge_graph_i_391600_idx"),
                ],
                "constraints": [models.UniqueConstraint(fields=("graph", "edge_id"), name="uniq_edge_per_graph")],
            },
        ),
        migrations.CreateModel(
            name="GraphCollaborator",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "role",
                    models.CharField(choices=[("read", "Read"), ("write", "Write")], default="read", max_length=8),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "graph",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="collaborators", to="graphs.graph"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="graph_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["graph", "user"],
                "constraints": [models.UniqueConstraint(fields=("graph", "user"), name="uniq_collaborator_per_graph")],
            },
        ),
        migrations.CreateModel(
            name="Node",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("node_id", models.CharField(max_length=200)),
                ("type", models.CharField(max_length=64)),
                ("status", models.CharField(blank=True, default="", max_length=32)),
                ("text", models.TextField(blank=True, default="")),
                ("data", models.JSONField()),
                (
                    "graph",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="nodes", to="graphs.graph"
                    ),
                ),
            ],
            options={
                "ordering": ["graph", "type", "node_id"],
                "indexes": [
                    models.Index(fields=["graph", "type"], name="graphs_node_graph_i_d08e55_idx"),
                    models.Index(fields=["graph", "status"], name="graphs_node_graph_i_5d2c56_idx"),
                ],
                "constraints": [models.UniqueConstraint(fields=("graph", "node_id"), name="uniq_node_per_graph")],
            },
        ),
    ]
